services:
  - type: web
    name: laravel-backend
    env: php
    plan: free
    buildCommand: |
      cd bh_backend
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_URL
        value: https://your-app-url.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: histories_6eia
          property: host
      - key: DB_PORT
        fromDatabase:
          name: histories_6eia
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: histories_6eia
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: histories_6eia
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: histories_6eia
          property: password
      - key: FRONTEND_URL
        sync: false
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
